### ISSUE TITLE
Build failure: defra-agent-cli mcp.rs:151 calls run_health_check_cycle with 6 args, signature takes 7

### ISSUE THREAD

**Issue by jackzampolin** [gents-ai/gents#331]
## Repro

```bash
cargo check
```

Fails with:

\`\`\`
error[E0061]: this function takes 7 arguments but 6 arguments were supplied
  --> crates/defra-agent-cli/src/commands/mcp.rs:151
\`\`\`

## Cause

PR #316 (\`5fd1b3d0\` — \"health_checker: add K>=2 MCP health backoff\") added a parameter to \`run_health_check_cycle\` in \`crates/defra-agent/src/health_checker.rs:335\` but didn't update the CLI caller at \`crates/defra-agent-cli/src/commands/mcp.rs:151\` (\`defra-agent mcp probe ...\` subcommand).

Reproduces against \`main\` independently of any feature branch.

## Why CI didn't catch it

Per-crate \`cargo test -p defra-agent\` passes (the health_checker tests work fine in isolation). The arity mismatch only surfaces at workspace-level \`cargo check\` because that's when the CLI binary links against the new signature. Worth adding a workspace \`cargo check\` job if one isn't already running on PRs.

## Suggested fix

One-liner: add the missing argument at the CLI call site. Consult the current 7-arg signature for what to pass; the per-service backoff K value (default 3) is presumably the new parameter.

## Found by

Discovered while doing workspace-level verification on PR #325 (#277 cancel UX bundle). Not introduced by that PR; pre-exists on main.

**Comment by jackzampolin** [comment]
Already resolved — the missing 8th argument (`persistence: Option<HealthPersistenceContext<'_>>`, added by #316 via the `K>=2` backoff work) landed at the CLI call site during PR #328's rebase pass.

Verified against current `main` (`7df348fc`):

- Signature at `crates/defra-agent/src/health_checker.rs:438` takes 8 args
- Call site at `crates/defra-agent-cli/src/commands/mcp.rs:151` passes 8 args: `vec![service], Utc::now(), pool, &health_map, local_hostname, local_subnet, &HealthCheckerOptions::default(), None`
- `cargo check -p defra-agent-cli` succeeds with no errors (warnings only)

Closing as fixed. The CI-coverage gap noted in the original report — workspace-level `cargo check` would have caught the divergence earlier — is still worth tracking separately if not already on the list.
